// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit the matching file under src/shared/ instead, then run `npm run sync:worker`.

'use strict';

const HUB_RESPONSE_HEADER = 'x-token-monitor-response';
const HUB_RESPONSE_MINIMAL = 'minimal';
const HUB_STREAM_HEADER = 'x-token-monitor-stream';
const HUB_STREAM_VERSION = '2';

function headerValue(source, name) {
  const headers = source?.headers || source;
  if (headers && typeof headers.get === 'function') return String(headers.get(name) || '').trim();
  const target = String(name).toLowerCase();
  for (const [key, value] of Object.entries(headers || {})) {
    if (String(key).toLowerCase() === target) return String(value || '').trim();
  }
  return '';
}

function wantsMinimalResponse(source) {
  return headerValue(source, HUB_RESPONSE_HEADER).toLowerCase() === HUB_RESPONSE_MINIMAL;
}

function wantsFreshnessEvents(source) {
  return headerValue(source, HUB_STREAM_HEADER) === HUB_STREAM_VERSION;
}

function acceptsEncoding(source, requestedEncoding) {
  const requested = String(requestedEncoding || '').trim().toLowerCase();
  if (!requested) return false;
  let wildcardQuality = null;
  for (const part of headerValue(source, 'accept-encoding').split(',')) {
    const [encoding, ...parameters] = part.toLowerCase().split(';').map((segment) => segment.trim());
    const qualityParameter = parameters.find((parameter) => parameter.startsWith('q='));
    const quality = qualityParameter ? Number(qualityParameter.slice(2)) : 1;
    const accepted = Number.isFinite(quality) && quality > 0 && quality <= 1;
    if (encoding === requested) return accepted;
    if (encoding === '*') wildcardQuality = accepted;
  }
  return wildcardQuality === true;
}

// These fields are regenerated by transport or aggregation. Everything else,
// including source timestamps inside limits and sessions, remains part of the
// content key so a real usage, limit, project, or history update stays visible.
function hubStatsContentKey(stats) {
  const { updatedAt: _updatedAt, limits, devices, ...rest } = stats || {};
  const { updatedAt: _limitsUpdatedAt, ...stableLimits } = limits || {};
  return JSON.stringify({
    ...rest,
    limits: stableLimits,
    devices: (devices || []).map((device) => {
      const {
        updatedAt: _deviceUpdatedAt,
        receivedAt: _receivedAt,
        ageMs: _ageMs,
        ...stableDevice
      } = device || {};
      return stableDevice;
    })
  });
}

function freshnessEvent(stats, reason = 'ingest', at = new Date().toISOString()) {
  const limitsUpdatedAt = stats?.limits?.updatedAt;
  return {
    type: 'freshness',
    reason,
    stats: {
      updatedAt: stats?.updatedAt || at,
      staleAfterMs: stats?.staleAfterMs,
      ...(limitsUpdatedAt ? { limits: { updatedAt: limitsUpdatedAt } } : {}),
      devices: (stats?.devices || []).map((device) => ({
        deviceId: device.deviceId,
        updatedAt: device.updatedAt,
        receivedAt: device.receivedAt,
        ageMs: device.ageMs,
        stale: device.stale
      }))
    },
    at
  };
}

function applyFreshnessEvent(stats, event) {
  if (!stats || !event?.stats) return stats;
  const byDeviceId = new Map((event.stats.devices || []).map((device) => [device.deviceId, device]));
  return {
    ...stats,
    ...(event.stats.updatedAt ? { updatedAt: event.stats.updatedAt } : {}),
    ...(Number.isFinite(event.stats.staleAfterMs) ? { staleAfterMs: event.stats.staleAfterMs } : {}),
    ...(event.stats.limits ? { limits: { ...(stats.limits || {}), ...event.stats.limits } } : {}),
    devices: (stats.devices || []).map((device) => {
      const freshness = byDeviceId.get(device.deviceId);
      return freshness ? { ...device, ...freshness } : device;
    })
  };
}

module.exports = {
  HUB_RESPONSE_HEADER,
  HUB_RESPONSE_MINIMAL,
  HUB_STREAM_HEADER,
  HUB_STREAM_VERSION,
  acceptsEncoding,
  applyFreshnessEvent,
  freshnessEvent,
  headerValue,
  hubStatsContentKey,
  wantsFreshnessEvents,
  wantsMinimalResponse
};
